name: Deploy PPA

on:
  push:
    branches: test-ppa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install curl git debhelper devscripts dput gpg
          sudo apt-get install bison flex curl make texinfo zlib1g-dev tar bzip2 gzip xz-utils unzip dos2unix libtool-bin gcc-9 g++-9
          echo "::set-env name=CC::gcc-9"
          echo "::set-env name=CXX::g++-9"

      - name: Download sources
        run: |
          ./build-djgpp.sh --batch --only-download --ignore-dependencies djgpp-cvs binutils gcc gdb

      - name: Install makefile
        run: |
          mv debian/Makefile .

      - name: Test build
        run: |
          debuild -us -uc

      - name: Move .deb files
        run: |
          mkdir -p debs
          mv ../*.deb ../*.ddeb debs/

      - name: Upload .deb files
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: debs
